# Generated by Django 5.1.1 on 2024-10-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_experience_main_resume_project_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='seen_count',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='seen_count',
            new_name='views',
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='views',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
