# Generated by Django 5.1.1 on 2024-10-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='desctiption',
            new_name='description',
        ),
    ]
